version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
    container_name: servicio_de_tizada_web
